service: feature-flags
frameworkVersion: '2'
provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
functions:
  feature-flags:
    handler: handler.index
    events:
      - http:
          path: /feature-flags/{feature}
          method: get
          request: 
            parameters: 
              paths:
                feature: true
